service:
  name: braintree-service

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  token:
    handler: get-token.handler
    events:
      - http:
          method: GET
          path: braintree/token
          cors: true
custom:
  stage: ${opt:stage, self:provider.stage}
  default_env: 'Sandbox'
