service:
  name: api-services

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, ${env:AWS_STAGE, 'dev'}}
  environment:
    AK_API_URL: ${env:AK_API_URL}
    AK_PASSWORD: ${env:AK_PASSWORD}
    AK_USERNAME: ${env:AK_USERNAME}
    BRAINTREE_ENVIRONMENT: ${env:BRAINTREE_ENV, 'sandbox'}
    BRAINTREE_MERCHANT_ID: ${env:BRAINTREE_MERCHANT_ID}
    BRAINTREE_PRIVATE_KEY: ${env:BRAINTREE_PRIVATE_KEY}
    BRAINTREE_PUBLIC_KEY: ${env:BRAINTREE_PUBLIC_KEY}
    GOCARDLESS_ENV: ${env:GOCARDLESS_ENV, 'sandbox'}
    GOCARDLESS_TOKEN: ${env:GOCARDLESS_TOKEN}

functions:
  members-list:
    handler: members-service/members.index
    events:
      - http:
          method: GET
          path: members
          cors: true
  members-show:
    handler: members-service/members.show
    events:
      - http:
          method: GET
          path: members/{id}
          cors: true
  members-update:
    handler: members-service/members.update
    events:
      - http:
          method: POST
          path: members/{id}
          cors: true
  members-unsubscribe:
    handler: members-service/members.unsubscribe
    events:
      - http:
          method: POST
          path: members/{id}/unsubscribe
          cors: true
  subscriptions-list:
    handler: payments-service/subscription.index
    events:
      - http:
          method: get
          path: subscription
          cors: true
  braintree-token:
    handler: payments-service/providers/braintree/token.handler
    events:
      - http:
          method: get
          path: braintree/token
          cors: true