service:
  name: api-services

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  region: eu-west-2
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.aws_stage}
  environment: ${self:custom.environment}

functions:
  members-list:
    handler: members-service/members.index
    events:
      - http:
          method: get
          path: members
          cors: true
  members-show:
    handler: members-service/members.show
    events:
      - http:
          method: get
          path: members/{id}
          cors: true
  members-update:
    handler: members-service/members.update
    events:
      - http:
          method: post
          path: members/{id}
          cors: true
  members-unsubscribe:
    handler: members-service/members.unsubscribe
    events:
      - http:
          method: post
          path: members/{id}/unsubscribe
          cors: true
  subscriptions-list:
    handler: payments-service/subscription.index
    events:
      - http:
          method: get
          path: subscriptions
          cors: true
  braintree-token:
    handler: payments-service/providers/braintree/token.handler
    events:
      - http:
          method: get
          path: braintree/token
          cors: true

custom:
  # Use the AWS_STAGE env var if you don't want to manually override the stage
  # via the command line. So, instead of:
  #
  #  $ sls deploy -s stageName -f functionName
  #  $ sls invoke -s stageName -f functionName
  #  $ sls logs -s stageName -f functionName
  #
  # You can set the stage in your env, and it will be picked up by sls:
  #
  #  $ export AWS_STAGE=stageName
  #  $ sls deploy -f functionName
  #  $ sls invoke -f functionName
  #  $ sls logs -f functionName
  #
  # If you don't set a stage, it will default to 'dev'
  aws_stage: ${env:AWS_STAGE, 'dev'}

  # By default, dev and prod stages use env vars. If you're deploying to your
  # own stage, create the file: {project_root}/settings/{your_stage_name}.yml
  # with the following format:
  #
  #     environment:
  #       KEY1: value1
  #       KEY2: value2
  #
  # And it will be picked up automatically
  environment: ${file(./settings/${self:provider.stage}.yml):environment}
