service:
  name: actionkit-service

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  main:
    handler: main.handler
  search:
    handler: search.handler
    events:
      - http:
          method: GET
          path: actionkit/search-users
          cors: true
