// flow-typed signature: 5fae7d5a03ad087f5ea1fd1c2c1fcc30
// flow-typed version: <<STUB>>/braintree-node_v^1.1.2/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'braintree-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'braintree-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'braintree-node/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'braintree-node/index' {
  declare module.exports: $Exports<'braintree-node'>;
}
declare module 'braintree-node/index.js' {
  declare module.exports: $Exports<'braintree-node'>;
}
declare module 'braintree-node/test.js' {
  declare module.exports: $Exports<'braintree-node/test'>;
}
