module.exports = {
  '000000': {
    status: 404,
    headers: {
      connection: 'keep-alive',
      'content-Encoding': 'gzip',
      'Content-Length': 20,
      'Content-Type': 'text/html; charset=utf-8',
      Date: 'Tue, 21 Nov 2017 18:36:51 GMT',
      Server: 'nginx',
      Vary: 'Accept,Cookie,Accept-Encoding,User-Agent',
      'X-Handled-For': '89.197.86.130',
      'X-Machine-Id': 'ip-10-50-2-105',
    },
  },
  388175: {
    status: 200,
    headers: {
      'cache-control': 'no-cache',
      connection: 'close',
      'content-type': 'application/json',
      date: 'Tue, 21 Nov 2017 17:57:07 GMT',
      server: 'nginx',
      'transfer-encoding': 'chunked',
      vary: 'Accept,Cookie,Accept-Encoding,User-Agent',
      'x-handled-for': '89.197.86.130',
      'x-machine-id': 'ip-10-50-2-213',
    },
    data: {
      actions: '/rest/v1/action/?user=388175',
      address1: '',
      address2: '',
      city: 'Philadelphia',
      country: 'United States',
      created_at: '2012-03-25T06:44:11',
      email: 'example@example.com',
      events: '/rest/v1/event/?creator=388175',
      eventsignups: '/rest/v1/eventsignup/?user=388175',
      fields: {
        en: '1',
      },
      first_name: 'Ashley',
      id: 388175,
      lang: '/rest/v1/language/100/',
      last_name: 'Mease',
      location: '/rest/v1/location/388175/',
      logintoken: '/rest/v1/user/388175/logintoken/',
      middle_name: '',
      orderrecurrings: '/rest/v1/orderrecurring/?user=388175',
      orders: '/rest/v1/order/?user=388175',
      phones: [],
      plus4: '',
      postal: '19145',
      prefix: '',
      rand_id: 692604506,
      region: '',
      resource_uri: '/rest/v1/user/388175/',
      source: 'starbucks 3/12',
      state: 'PA',
      subscription_status: 'bounced',
      subscriptionhistory: '/rest/v1/subscriptionhistory/?user=388175',
      subscriptions: '/rest/v1/subscription/?user=388175',
      suffix: '',
      token: '.388175.onPRSf',
      updated_at: '2017-01-31T00:07:52',
      usergeofields: '/rest/v1/usergeofield/?user=388175',
      usermailings: '/rest/v1/usermailing/?user=388175',
      useroriginal: '/rest/v1/useroriginal/388175/',
      zip: '19145',
    },
  },
  email__startswith: {
    status: 400,
    headers: {
      'cache-control': 'no-cache',
      connection: 'close',
      'content-type': 'application/json',
      date: 'Tue, 21 Nov 2017 17:57:07 GMT',
      server: 'nginx',
      'transfer-encoding': 'chunked',
      vary: 'Accept,Cookie,Accept-Encoding,User-Agent',
      'x-handled-for': '89.197.86.130',
      'x-machine-id': 'ip-10-50-2-213',
    },
    data: {
      error: "'startswith' is not an allowed filter on the 'email' field.",
    },
  },
  'nonexistentuser@example.com': {
    status: 200,
    headers: {
      'cache-control': 'no-cache',
      connection: 'close',
      'content-type': 'application/json',
      date: 'Tue, 21 Nov 2017 17:57:07 GMT',
      server: 'nginx',
      'transfer-encoding': 'chunked',
      vary: 'Accept,Cookie,Accept-Encoding,User-Agent',
      'x-handled-for': '89.197.86.130',
      'x-machine-id': 'ip-10-50-2-213',
    },
    data: {
      meta: {
        limit: 20,
        next: null,
        offset: 0,
        previous: null,
        total_count: 0,
      },
      objects: [],
    },
  },
  'example@example.com': {
    status: 200,
    headers: {
      'cache-control': 'no-cache',
      connection: 'close',
      'content-type': 'application/json',
      date: 'Tue, 21 Nov 2017 17:57:07 GMT',
      server: 'nginx',
      'transfer-encoding': 'chunked',
      vary: 'Accept,Cookie,Accept-Encoding,User-Agent',
      'x-handled-for': '89.197.86.130',
      'x-machine-id': 'ip-10-50-2-213',
    },
    data: {
      meta: {
        limit: 20,
        next: null,
        offset: 0,
        previous: null,
        total_count: 1,
      },
      objects: [
        {
          actions: '/rest/v1/action/?user=388175',
          address1: '',
          address2: '',
          city: 'Philadelphia',
          country: 'United States',
          created_at: '2012-03-25T06:44:11',
          email: 'example@example.com',
          events: '/rest/v1/event/?creator=388175',
          eventsignups: '/rest/v1/eventsignup/?user=388175',
          fields: {
            en: '1',
          },
          first_name: 'Ashley',
          id: 388175,
          lang: '/rest/v1/language/100/',
          last_name: 'Mease',
          location: '/rest/v1/location/388175/',
          logintoken: '/rest/v1/user/388175/logintoken/',
          middle_name: '',
          orderrecurrings: '/rest/v1/orderrecurring/?user=388175',
          orders: '/rest/v1/order/?user=388175',
          phones: [],
          plus4: '',
          postal: '19145',
          prefix: '',
          rand_id: 692604506,
          region: '',
          resource_uri: '/rest/v1/user/388175/',
          source: 'starbucks 3/12',
          state: 'PA',
          subscription_status: 'bounced',
          subscriptionhistory: '/rest/v1/subscriptionhistory/?user=388175',
          subscriptions: '/rest/v1/subscription/?user=388175',
          suffix: '',
          token: '.388175.onPRSf',
          updated_at: '2017-01-31T00:07:52',
          usergeofields: '/rest/v1/usergeofield/?user=388175',
          usermailings: '/rest/v1/usermailing/?user=388175',
          useroriginal: '/rest/v1/useroriginal/388175/',
          zip: '19145',
        },
      ],
    },
  },
};
