# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/api-services

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-y{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-y{{ checksum "package-lock.json" }}

      - run: source .env.test && npm run ci:test
      - run: npm run ci:coveralls
      - run: npm run flow check

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "${STAGING_DEPLOY_BRANCH}" ]; then
              echo "Deploying to STAGING"
              ./deploy/deploy.sh staging
            elif [ "${CIRCLE_BRANCH}" == "${PRODUCTION_DEPLOY_BRANCH}" ]; then
              echo "Deploying to PRODUCTION"
              ./deploy/deploy.sh production
            fi

