environment:
  AK_API_URL: ${ssm:/api-services/production/AK_API_URL}
  AK_PASSWORD: ${ssm:/api-services/production/AK_PASSWORD}
  AK_USERNAME: ${ssm:/api-services/production/AK_USERNAME}
  BRAINTREE_ENV: ${ssm:/api-services/production/BRAINTREE_ENV}
  BRAINTREE_MERCHANT_ID: ${ssm:/api-services/production/BRAINTREE_MERCHANT_ID}
  BRAINTREE_PRIVATE_KEY: ${ssm:/api-services/production/BRAINTREE_PRIVATE_KEY}
  BRAINTREE_PUBLIC_KEY: ${ssm:/api-services/production/BRAINTREE_PUBLIC_KEY}
  GOCARDLESS_ENV: ${ssm:/api-services/production/GOCARDLESS_ENV}
  GOCARDLESS_TOKEN: ${ssm:/api-services/production/GOCARDLESS_TOKEN}
  CHAMPAIGN_URL: ${ssm:/api-services/production/CHAMPAIGN_URL}
  MEMBER_SERVICES_SECRET: ${ssm:/api-services/production/MEMBER_SERVICES_SECRET}
  DB_LOG_TABLE: ${ssm:/api-services/production/DB_LOG_TABLE}
  UNSUBSCRIBE_PAGE_NAME: ${ssm:/api-services/production/UNSUBSCRIBE_PAGE_NAME}
  BRAINTREE_MERCHANT_CURRENCIES: ${ssm:/api-services/production/BRAINTREE_MERCHANT_CURRENCIES}
  COGNITO_POOL_ARN: ${ssm:/api-services/production/COGNITO_POOL_ARN}
  AK_MYSQL_HOST: ${ssm:/api-services/AK_MYSQL_HOST}
  AK_MYSQL_USER: ${ssm:/api-services/AK_MYSQL_USER}
  AK_MYSQL_PWD: ${ssm:/api-services/AK_MYSQL_PWD}
  AK_MYSQL_DB: ${ssm:/api-services/AK_MYSQL_DB}
  MEMBER_SERVICES_EMAIL: ${ssm:/api-services/production/MEMBER_SERVICES_EMAIL}

