environment:
  AK_API_URL: ${env:AK_API_URL}
  AK_PASSWORD: ${env:AK_PASSWORD}
  AK_USERNAME: ${env:AK_USERNAME}
  BRAINTREE_ENV: Sandbox
  BRAINTREE_MERCHANT_ID: ${env:BRAINTREE_MERCHANT_ID}
  BRAINTREE_PRIVATE_KEY: ${env:BRAINTREE_PRIVATE_KEY}
  BRAINTREE_PUBLIC_KEY: ${env:BRAINTREE_PUBLIC_KEY}
  GOCARDLESS_ENV: sandbox
  GOCARDLESS_TOKEN: ${env:GOCARDLESS_TOKEN}
  CHAMPAIGN_URL: ${env:CHAMPAIGN_URL}
  MEMBER_SERVICES_SECRET: ${env:MEMBER_SERVICES_SECRET}
  DB_LOG_TABLE: ${env:DB_LOG_TABLE}
