environment:
  AK_API_URL: ${ssm:/api-services/staging/AK_API_URL}
  AK_PASSWORD: ${ssm:/api-services/staging/AK_PASSWORD}
  AK_USERNAME: ${ssm:/api-services/staging/AK_USERNAME}
  BRAINTREE_ENV: Sandbox
  BRAINTREE_MERCHANT_ID: ${ssm:/api-services/staging/BRAINTREE_MERCHANT_ID}
  BRAINTREE_PRIVATE_KEY: ${ssm:/api-services/staging/BRAINTREE_PRIVATE_KEY}
  BRAINTREE_PUBLIC_KEY: ${ssm:/api-services/staging/BRAINTREE_PUBLIC_KEY}
  GOCARDLESS_ENV: sandbox
  GOCARDLESS_TOKEN: ${ssm:/api-services/staging/GOCARDLESS_TOKEN}
  CHAMPAIGN_URL: ${ssm:/api-services/staging/CHAMPAIGN_URL}
  MEMBER_SERVICES_SECRET: ${ssm:/api-services/staging/MEMBER_SERVICES_SECRET}
  DB_LOG_TABLE: ${ssm:/api-services/staging/DB_LOG_TABLE}
  UNSUBSCRIBE_PAGE_NAME: ${ssm:/api-services/staging/UNSUBSCRIBE_PAGE_NAME}
  BRAINTREE_MERCHANT_CURRENCIES: ${ssm:/api-services/staging/BRAINTREE_MERCHANT_CURRENCIES}
  COGNITO_POOL_ARN: ${ssm:/api-services/staging/COGNITO_POOL_ARN}
  AK_MYSQL_HOST: ${ssm:/api-services/staging/AK_MYSQL_HOST}
  AK_MYSQL_USER: ${ssm:/api-services/staging/AK_MYSQL_USER}
  AK_MYSQL_PWD: ${ssm:/api-services/staging/AK_MYSQL_PWD}
  AK_MYSQL_DB: ${ssm:/api-services/staging/AK_MYSQL_DB}
  MEMBER_SERVICES_EMAIL: ${ssm:/api-services/staging/MEMBER_SERVICES_EMAIL}
