service:
  name: actionkit-service

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${env:AWS_STAGE, 'dev'}
  environment:
    AK_API_URL: ${env:AK_API_URL}
    AK_USERNAME: ${env:AK_USERNAME}
    AK_PASSWORD: ${env:AK_PASSWORD}

functions:
  members-list:
    handler: members.index
    events:
      - http:
          method: GET
          path: members
          cors: true
  members-show:
    handler: members.show
    events:
      - http:
          method: GET
          path: members/{id}
          cors: true
  members-update:
    handler: members.update
    events:
      - http:
          method: POST
          path: members/{id}
          cors: true
  members-unsubscribe:
    handler: members.unsubscribe
    events:
      - http:
          method: POST
          path: members/{id}/unsubscribe
          cors: true